default: &default
  adapter: postgis
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: startupx_development
  schema_search_path: "public,postgis"

test:
  <<: *default
  database: startupx_test
  schema_search_path: "public,postgis"

production:
  <<: *default
  database: startupx_production
  schema_search_path: "public,postgis"
  username: startupx
  password: <%= ENV['STARTUPX_DATABASE_PASSWORD'] %>
